<?php
return array (
  'site_name' => '家里蹲',
  'site_company' => '家里蹲网络',
  'site_companyurl' => 'http://',
  'site_adminfile' => 'admin.php',
  'site_icp' => '',
  'site_status' => '1',
  'site_countcode' => '',
  'site_logo' => '',
  'site_subtitle' => '',
  'site_keywords' => '',
  'site_description' => '',
  'site_headecode' => '',
  'site_watermarkurl' => '',
  'site_watermarkposition' => '0',
  'site_watermarkalignment' => '',
  'site_integralname' => '',
  'site_integralexchange' => '',
  'site_zone' => '0',
  'site_dataformat' => '',
  'site_timeformat' => '0',
  'site_gzip' => '0',
  'site_rwrite' => '0',
); 